# Generated by Django 5.1.6 on 2025-03-01 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_alter_language_options_alter_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, verbose_name='Plat Nomor')),
                ('vehicle_type', models.CharField(choices=[('MOTOR', 'Motor'), ('MOBIL', 'Mobil'), ('TRUK', 'Truk')], default='MOTOR', max_length=10, verbose_name='Jenis Kendaraan')),
                ('color', models.CharField(max_length=50, verbose_name='Warna Kendaraan')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Waktu Masuk')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Kendaraan Masuk',
                'verbose_name_plural': 'Kendaraan Masuk',
            },
        ),
    ]
